# Generated by Django 5.2.17 on 2026-09-23 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('esta_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"eventos"."categorias_evento"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_publico', models.CharField(max_length=80, unique=True)),
                ('hash_token_qr', models.CharField(max_length=255, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('UTILIZADA', 'Utilizada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], db_index=True, default='ACTIVA', max_length=20)),
                ('emitida_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilizada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"eventos"."entradas"',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('codigo_pais', models.CharField(blank=True, db_index=True, max_length=3)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"eventos"."lugares"',
                'ordering': ['ciudad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EscaneoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_token_escaneado', models.CharField(blank=True, db_index=True, max_length=255)),
                ('resultado', models.CharField(choices=[('VALIDO', 'Válido'), ('YA_UTILIZADO', 'Ya utilizado'), ('INVALIDO', 'Inválido'), ('CANCELADO', 'Cancelado'), ('EVENTO_INCORRECTO', 'Evento incorrecto'), ('EXPIRADO', 'Expirado')], max_length=30)),
                ('escaneado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('informacion_dispositivo', models.CharField(blank=True, max_length=255)),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos', to='eventos.entrada')),
                ('escaneado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escaneos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"eventos"."escaneos_entrada"',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metodo', models.CharField(default='QR', max_length=20)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='eventos.entrada')),
                ('escaneo_valido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencia_generada', to='eventos.escaneoentrada')),
            ],
            options={
                'db_table': '"eventos"."asistencias"',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('identificador_url', models.SlugField(max_length=220, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=20)),
                ('visibilidad', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PUBLICO', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], db_index=True, default='BORRADOR', max_length=20)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(db_index=True)),
                ('fecha_hora_fin', models.DateTimeField()),
                ('inicio_inscripciones', models.DateTimeField(blank=True, null=True)),
                ('cierre_inscripciones', models.DateTimeField(blank=True, null=True)),
                ('url_virtual', models.URLField(blank=True, max_length=500)),
                ('url_imagen_portada', models.URLField(blank=True, max_length=500)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.categoriaevento')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.lugar')),
            ],
            options={
                'db_table': '"eventos"."eventos"',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='escaneoentrada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to='eventos.evento'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente'), ('CANCELADA', 'Cancelada')], db_index=True, default='CONFIRMADA', max_length=20)),
                ('inscrito_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"eventos"."inscripciones"',
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='eventos.inscripcion'),
        ),
        migrations.CreateModel(
            name='MiembroEquipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('asignado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_equipo_realizadas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='eventos.evento')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miembros_eventos', to='cuentas.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"eventos"."miembros_equipo_evento"',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=30)),
                ('esta_leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"eventos"."notificaciones"',
            },
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cupo', models.PositiveIntegerField(blank=True, null=True)),
                ('inicio_disponibilidad', models.DateTimeField(blank=True, null=True)),
                ('fin_disponibilidad', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_entrada', to='eventos.evento')),
            ],
            options={
                'db_table': '"eventos"."tipos_entrada"',
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='eventos.tipoentrada'),
        ),
        migrations.AddIndex(
            model_name='escaneoentrada',
            index=models.Index(fields=['evento', 'escaneado_en'], name='ix_escaneo_evento_fecha'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['evento', 'estado'], name='ix_insc_evento_estado'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('evento', 'usuario'), name='uq_inscripcion_evento_usuario'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['estado', 'fecha_hora_inicio'], name='ix_evento_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='miembroequipoevento',
            constraint=models.UniqueConstraint(fields=('evento', 'usuario', 'rol'), name='uq_equipo_evento_usuario_rol'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'esta_leida'], name='ix_notif_usuario_leida'),
        ),
        migrations.AddConstraint(
            model_name='tipoentrada',
            constraint=models.UniqueConstraint(fields=('evento', 'nombre'), name='uq_tipo_entrada_evento_nombre'),
        ),
    ]
