# Generated by Django 5.2.17 on 2026-09-23 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('tipo_entidad', models.CharField(blank=True, max_length=80)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"auditoria"."registros_actividad"',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tipo_entidad', 'entidad_id'], name='ix_audit_entidad')],
            },
        ),
    ]
