# Generated by Django 5.2.17 on 2026-09-23 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('url_imagen_perfil', models.URLField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=20)),
                ('es_staff_django', models.BooleanField(default=False)),
                ('es_superusuario', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"autenticacion"."usuarios"',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"autenticacion"."permisos"',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"autenticacion"."roles"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_token', models.CharField(max_length=255, unique=True)),
                ('expira_en', models.DateTimeField()),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('agente_usuario', models.CharField(blank=True, max_length=500)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_refresh', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"autenticacion"."sesiones_refresh"',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roles', to='cuentas.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_permisos', to='cuentas.rol')),
            ],
            options={
                'db_table': '"autenticacion"."rol_permisos"',
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rol_permiso')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_usuarios', to='cuentas.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"autenticacion"."usuario_roles"',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol')],
            },
        ),
    ]
